version: "3.9"

services:
  postgres:
    image: postgres:16-alpine
    container_name: yummy-postgres
    environment:
      POSTGRES_DB: yummyfood
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ZAQ!2wsx
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d yummyfood"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: yummy-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/yummyfood
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: ZAQ!2wsx
      SPRING_JPA_HIBERNATE_DDL_AUTO: update      # na dev można tak
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: yummy-frontend
  #   depends_on:
  #     - backend
  #   ports:
  #     - "5173:80"   # jeśli serwujesz przez nginx
  #   environment:
  #     VITE_API_BASE_URL: "http://localhost:8080"

volumes:
  pgdata:
