apiVersion: apps/v1
kind: Deployment
metadata:
  name: yummy-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yummy-backend
  template:
    metadata:
      labels:
        app: yummy-backend
    spec:
      containers:
        - name: yummy-backend
          image: yummy-backend:1.0.2
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/yummyfood
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: postgres-password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_PROFILES_ACTIVE
              value: docker
